# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "bulk-opretion"
client_id = "ba5e4c548a6994fea84ca96cecb28a1c"
application_url = "https://rendering-fotos-researcher-kick.trycloudflare.com"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://rendering-fotos-researcher-kick.trycloudflare.com/auth/callback",
  "https://rendering-fotos-researcher-kick.trycloudflare.com/auth/shopify/callback",
  "https://rendering-fotos-researcher-kick.trycloudflare.com/api/auth/callback",
  "https://rendering-fotos-researcher-kick.trycloudflare.com/.shopify/graphiql/auth/callback"
]

[webhooks]
api_version = "2023-10"

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = true
dev_store_url = "appmixo-disha.myshopify.com"
